version: "3.1"
services:
  worker:
    image: pushsign/hasd-worker:local
    restart: "no"
    command: "node index.js"
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: postgres
      PGDATABASE: herearesomedogs
      PGPORT: 5432
      GIT_TREE_URL: https://api.github.com/repos/deeja/dog-api-images/git/trees/master?recursive=1
  db:
    image: pushsign/hasd-db:local
    restart: always
    expose:
      - "5432"
    volumes:
      - "hasd_db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data"
volumes:
  hasd_db_data:
    driver: local
